[[faq]]
[appendix]
= Frequently Asked Questions

== Common

[qanda]
I'd like to get more detailed logging information on what methods are called inside `JpaRepository` (for exmaple). How can I gain them? :: You can make use of `CustomizableTraceInterceptor` provided by Spring, as shown in the following example:
+
[source, xml]
----
<bean id="customizableTraceInterceptor" class="
  org.springframework.aop.interceptor.CustomizableTraceInterceptor">
  <property name="enterMessage" value="Entering $[methodName]($[arguments])"/>
  <property name="exitMessage" value="Leaving $[methodName](): $[returnValue]"/>
</bean>

<aop:config>
  <aop:advisor advice-ref="customizableTraceInterceptor"
    pointcut="execution(public * org.springframework.data.jpa.repository.JpaRepository+.*(..))"/>
</aop:config>
----

== Infrastructure

[qanda]
Currently I have implemented a repository layer based on `HibernateDaoSupport`. I create a `SessionFactory` by using Spring's `AnnotationSessionFactoryBean`. How do I get Spring Data repositories working in this environment? :: You have to replace `AnnotationSessionFactoryBean` with the `HibernateJpaSessionFactoryBean`, as follows:
+
.Looking up a `SessionFactory` from a `HibernateEntityManagerFactory`
====
[source, xml]
----
<bean id="sessionFactory" class="org.springframework.orm.jpa.vendor.HibernateJpaSessionFactoryBean">
  <property name="entityManagerFactory" ref="entityManagerFactory"/>
</bean>
----
====

== Auditing

[qanda]
I want to use Spring Data JPA auditing capabilities but have my database already configured to set modification and creation date on entities. How can I prevent Spring Data from setting the date programmatically. :: Set the `set-dates` attribute of the `auditing` namespace element to `false`.

== Querydsl

Since version 2.0.x the querydsl classes `QAbstractPersistable` and `QAbstractAuditable` are not included in the *spring-data-jpa* jar anymore.

This will probably lead to compile errors in the generated Q-classes, stating that a class `QAbstractPersistable` is missing.

====
[source, bash]
----
... cannot find symbol
    public final org.springframework.data.jpa.domain.QAbstractPersistable _super = new org.springframework.data.jpa.domain.QAbstractPersistable(this);
                                                    ^
  symbol:   class QAbstractPersistable
  location: package org.springframework.data.jpa.domain

----
====

This problem can be fixed by providing a `package-info.java` in your domain package with the following content.

====
[source, java]
----
@QueryEntities(value = {AbstractPersistable.class, AbstractAuditable.class})
package <your-domain-package>;

import com.querydsl.core.annotations.QueryEntities;
import org.springframework.data.jpa.domain.AbstractAuditable;
import org.springframework.data.jpa.domain.AbstractPersistable;
----
====

This will instruct the *querydsl/mysema apt-maven-plugin* to include the stated classes in the generation step.