[[new-features]]
= New & Noteworthy

[[new-features.2-5-0]]
== What's New in Spring Data JPA 2.5

There is a new `getById` method in the `JpaRepository` which will replace `getOne`, which is now deprecated.
Since this method returns a reference this changes the behaviour of an existing `getById` method which before was implemented by query derivation.
This in turn might lead to an unexpected `LazyLoadingException` when accessing attributes of that reference outside a transaction.
To avoid this please rename your existing `getById` method to `getXyzById` with `Xyz` being an arbitrary string.

[[new-features.1-11-0]]
== What's New in Spring Data JPA 1.11

Spring Data JPA 1.11 added the following features:

* Improved compatibility with Hibernate 5.2.
* Support any-match mode for <<query-by-example>>.
* Paged query optimizations.
* Support for the `exists` projection in repository query derivation.

[[new-features.1-10-0]]
== What's New in Spring Data JPA 1.10

Spring Data JPA 1.10 added the following features:

* Support for <<projections>> in repository query methods.
* Support for <<query-by-example>>.
* The following annotations have been enabled to build on composed annotations: `@EntityGraph`, `@Lock`, `@Modifying`, `@Query`, `@QueryHints`, and `@Procedure`.
* Support for the `Contains` keyword on collection expressions.
* `AttributeConverter` implementations for `ZoneId` of JSR-310 and ThreeTenBP.
* Upgrade to Querydsl 4, Hibernate 5, OpenJPA 2.4, and EclipseLink 2.6.1.
