[appendix]
[[faq]]
= Frequently Asked Questions

[[faq.common]]
== Common

[qanda]
I'd like to get more detailed logging information on what methods are called inside `JpaRepository` for example. How can I gain them? :: You can make use of `CustomizableTraceInterceptor` provided by Spring, as shown in the following example:
+
[source, xml]
----
<bean id="customizableTraceInterceptor" class="
  org.springframework.aop.interceptor.CustomizableTraceInterceptor">
  <property name="enterMessage" value="Entering $[methodName]($[arguments])"/>
  <property name="exitMessage" value="Leaving $[methodName](): $[returnValue]"/>
</bean>

<aop:config>
  <aop:advisor advice-ref="customizableTraceInterceptor"
    pointcut="execution(public * org.springframework.data.jpa.repository.JpaRepository+.*(..))"/>
</aop:config>
----

[[faq.auditing]]
== Auditing

[qanda]
I want to use Spring Data JPA auditing capabilities but have my database already configured to set modification and creation date on entities. How can I prevent Spring Data from setting the date programmatically? :: Set the `set-dates` attribute of the `auditing` namespace element to `false`.


[[faq.hibernate]]
== Hibernate

[qanda]
Can I use Hibernate 8 with Spring Data JPA? :: Spring Data JPA currently relies on JPA 3.2 and Hibernate 7, but offers best-effort support for preview releases of Hibernate 8 (Beta1) and Jakarta Persistence 4.0 (M5).
