[[locking]]
= Locking

To specify the lock mode to be used, you can use the `@Lock` annotation on query methods, as shown in the following example:

.Defining lock metadata on query methods
====
[source, java]
----
interface UserRepository extends Repository<User, Long> {

  // Plain query method
  @Lock(LockModeType.READ)
  List<User> findByLastname(String lastname);
}
----
====

This method declaration causes the query being triggered to be equipped with a `LockModeType` of `READ`. You can also define locking for CRUD methods by redeclaring them in your repository interface and adding the `@Lock` annotation, as shown in the following example:

.Defining lock metadata on CRUD methods
====
[source, java]
----
interface UserRepository extends Repository<User, Long> {

  // Redeclaration of a CRUD method
  @Lock(LockModeType.READ)
  List<User> findAll();
}
----
====

In addition to the above examples, you can also define locking for specific query methods using different lock modes. The following example shows how to use `LockModeType.PESSIMISTIC_WRITE` for a query method:

.Defining pessimistic lock metadata on query methods
====
[source, java]
----
interface UserRepository extends JpaRepository<User, Long> {

    @Lock(LockModeType.PESSIMISTIC_WRITE)
    @Query("select u from User u where u.id = :id")
    User findByIdWithLock(@Param("id") Long id);
}
----
====

This method declaration causes the query to be equipped with a `LockModeType` of `PESSIMISTIC_WRITE`, ensuring that the record is locked for writing until the transaction is completed. This prevents other transactions from modifying the record simultaneously.

.Defining optimistic lock metadata on query methods
====
[source, java]
----
interface UserRepository extends JpaRepository<User, Long> {

    @Lock(LockModeType.OPTIMISTIC)
    @Query("select u from User u where u.id = :id")
    User findByIdWithOptimisticLock(@Param("id") Long id);
}
----
====
