DROP TABLE IF EXISTS with_vector;;

CREATE TABLE IF NOT EXISTS with_vector
(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    country       varchar2(10),
    description   varchar2(10),
    distance      varchar2(10),
    the_embedding vector(5, FLOAT32) annotations(Distance 'COSINE', IndexType 'IVF')
);;

create
vector index if not exists vector_index_1 on with_vector (the_embedding)
							organization neighbor partitions
									distance COSINE
with target accuracy 95
									parameters (type IVF, neighbor partitions 10);;
