name: CI Build

on:
  workflow_dispatch:
  push:
    branches: [ main, 'issue/**' ]

permissions: read-all

jobs:
  build-java:
    strategy:
      matrix:
        include:
          - java-version: base
            profiles: -Pall-dbs
          - java-version: main
            profiles: -Pall-dbs
          - java-version: main
            profiles: -Pall-dbs,hibernate-8
    name: Build project (${{ matrix.java-version }}, ${{ matrix.profiles }})
    runs-on: ${{ vars.ACTION_RUNNER || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java and Maven
        uses: spring-projects/spring-data-build/actions/setup-maven@main
        with:
          java-version: ${{ matrix.java-version }}
          develocity-access-key: '${{ secrets.DEVELOCITY_ACCESS_KEY }}'
      - name: Build
        uses: spring-projects/spring-data-build/actions/maven-build@main
        env:
          OSS_ARTIFACTORY_USR: '${{ secrets.ARTIFACTORY_USERNAME }}'
          OSS_ARTIFACTORY_PSW: '${{ secrets.ARTIFACTORY_PASSWORD }}'
          COMMERCIAL_ARTIFACTORY_USR: '${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}'
          COMMERCIAL_ARTIFACTORY_PSW: '${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}'
        with:
          additional-options: ${{ matrix.profiles }}
          settings-xml: '${{ vars.SETTINGS_XML }}'
