name: Snapshots

on:
  workflow_dispatch:
  push:
    branches: [ 4.0.x, 'issue/4.0.x/**', 'release/**' ]

permissions: read-all

jobs:
  build-snapshots:
    name: Build and deploy snapshots
    if: ${{ github.repository_owner == 'spring-projects' }}
    runs-on: ${{ vars.ACTION_RUNNER || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java and Maven
        uses: spring-projects/spring-data-build/actions/setup-maven@4.0.x
        with:
          develocity-access-key: '${{ secrets.DEVELOCITY_ACCESS_KEY }}'
      - name: Deploy to Artifactory
        uses: spring-projects/spring-data-build/actions/maven-artifactory-deploy@4.0.x
        env:
          OSS_ARTIFACTORY_USR: '${{ secrets.ARTIFACTORY_USERNAME }}'
          OSS_ARTIFACTORY_PSW: '${{ secrets.ARTIFACTORY_PASSWORD }}'
          COMMERCIAL_ARTIFACTORY_USR: '${{ secrets.COMMERCIAL_ARTIFACTORY_USERNAME }}'
          COMMERCIAL_ARTIFACTORY_PSW: '${{ secrets.COMMERCIAL_ARTIFACTORY_PASSWORD }}'
        with:
          build-name: 'spring-data-jpa'
          settings-xml: '${{ vars.SETTINGS_XML }}'
