name: Snapshots

on:
  workflow_dispatch:
  push:
    branches: [ 3.5.x, 'issue/3.5.x/**' ]

permissions: read-all

jobs:
  build-snapshots:
    name: Build and deploy snapshots
    if: ${{ github.repository_owner == 'spring-projects' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Java and Maven
        uses: spring-projects/spring-data-build/actions/setup-maven@3.5.x
        with:
          develocity-access-key: '${{ secrets.DEVELOCITY_ACCESS_KEY }}'
      - name: Deploy to Artifactory
        uses: spring-projects/spring-data-build/actions/maven-artifactory-deploy@3.5.x
        with:
          build-name: 'spring-data-jpa'
          username: '${{ secrets.ARTIFACTORY_USERNAME }}'
          password: '${{ secrets.ARTIFACTORY_PASSWORD }}'
