name: Build Release
runs:
  using: composite
  steps:
    - name: Write settings.xml
      if: ${{ env.RELEASE_TRAIN_SETTINGS_XML != '' }}
      shell: bash
      run: |
        echo "::notice::Writing provided settings-xml input to release-train-settings.xml"
        echo "${RELEASE_TRAIN_SETTINGS_XML}" > release-train-settings.xml
    - name: Prepare Maven command
      shell: bash
      run: |
        MAVEN_LOGGING_OPTS=()
        if [[ "${RUNNER_DEBUG}" == "1" || "${ACTIONS_STEP_DEBUG}" == "true" ]]; then
          echo "::notice::transfer-progress enabled"
        else
          MAVEN_LOGGING_OPTS+=(--no-transfer-progress)
        fi

        echo "RELEASE_TRAIN_MVN=./mvnw --batch-mode ${MAVEN_LOGGING_OPTS[*]} --settings release-train-settings.xml clean deploy -DaltDeploymentRepository=release-train::file://$(pwd)/deployment-repository -DskipTests -Dgpg.skip" >> "${GITHUB_ENV}"
    - name: Build Release
      shell: bash
      run: ${RELEASE_TRAIN_MVN} --activate-profiles releaseTrain,release,ci
    - name: Distribution build
      shell: bash
      run: ${RELEASE_TRAIN_MVN} --activate-profiles releaseTrain,distribute
    - name: Schema build
      shell: bash
      run: ${RELEASE_TRAIN_MVN} --activate-profiles releaseTrain,distribute-schema
